apps/user_dashboard/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^signin/$', views.signin, name="signin"),
    url('^authenticate/$', views.authenticate, name="authenticate"),
    url('^register/$', views.register, name="register"),
    url('^register_add/$', views.register_add, name="register_add"),
    url('^dashboard/$', views.dashboard, name="dashboard"),
    url('^dashboard/admin/$', views.dashboard_admin, name="dashboard_admin"),
    url('^logout/$', views.logout, name="logout"),
    url('^users/show/(?P<id>\d+)/$', views.show, name="show"),
    url('^users/message/(?P<id>\d+)/$', views.message, name="message"),
    url('^users/message/(?P<user_id>\d+)/delete/(?P<message_id>\d+)$', views.delete_message, name="delete_message"),
    url('^users/comment/(?P<user_id>\d+)/delete/(?P<comment_id>\d+)/$', views.delete_comment, name="delete_comment"),
    url('^users/comment/(?P<user_id>\d+)/(?P<message_id>\d+)/$', views.comment, name="comment"),
    url('^users/edit/(?P<id>\d+)/$', views.edit_admin, name="edit_admin"),
    url('^users/show/edit/$', views.edit, name="edit"),
    url('^users/show/update/(?P<id>\d+)/$', views.update, name="update"),
    url('^users/new/$', views.new, name="new"),
]

user_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('^', include('apps.user_dashboard.urls', namespace="dashboard")),
    url(r'^admin/', admin.site.urls),
]

apps/user_dashboard/models.py
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

class UserManager(models.Manager):
    def name_invalid(self, name):
        if not len(name) < 2 and re.search(r'^[a-zA-Z]+$', name):
            return False
        else:
            return True
    def email_invalid(self, email):
        email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if email_regex.match(email):
            return False
        else:
            return True
    def password_invalid(self, password):
        if len(password) < 8:
            return True
        else:
            return False
    def password_not_match(self, password, confirm_password):
        if password == confirm_password:
            return False
        else:
            return True

    def reg_validator(self, first_name, last_name, email, password, confirm_password):
        errors = []
        if self.name_invalid(first_name):
            errors.append("First name must be more than two characters and only letters")
        if self.name_invalid(last_name):
            errors.append("Last name must be more than two characters and only letters")
        if self.email_invalid(email):
            errors.append("Invalid email")
        if self.password_invalid(password):
            errors.append("Password must be 8 characters or more")
        if self.password_not_match(password, confirm_password):
            errors.append("Passwords must match")
        return errors
## returns an object with either {errors: list of errors}, or {user: user object}
    def add_user(self, first_name, last_name, email, password, confirm_password):
        errors = self.reg_validator(first_name, last_name, email, password, confirm_password)
        if errors:
            return {'errors': errors}
        else:
            hash_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            if not User.objects.all():
                user_level = 9
            else:
                user_level = 1
            try:
                user = User(first_name=first_name, last_name=last_name, email=email, hash_pw=hash_pw, user_level=user_level)
                user.save()
                return {"user": user}
            except:
                return {"errors": ["Email already registered"]}
## returns an object with either {errors: list of errors}, or {user: user object}
    def login(self, email, password):
        try:
            user = User.objects.get(email=email)
            if bcrypt.hashpw(password.encode(), user.hash_pw.encode()) == user.hash_pw:
                return {"user": user}
            else:
                return {"errors": ["Invalid email or password"]}
        except:
            return {"errors": ["Invalid email or password"]}

    def update_name(self, email, first_name, last_name, id, user_level=1):
        errors = []
        if self.email_invalid(email):
            errors.append("Invalid email")
        if self.name_invalid(first_name):
            errors.append("First name must be more than two characters and only letters")
        if self.name_invalid(last_name):
            errors.append("Last name must be more than two characters and only letters")
        if errors:
            return {'errors': errors}
        user = User.objects.get(id=id)
        user.first_name = first_name
        user.last_name = last_name
        if user.email == email:
            pass
        elif User.objects.filter(email=email):
            return {"errors": ["Email already registered"]}
        user.email = email
        if user_level > 0:
            user.user_level = user_level
        user.save()
        return {"user": user}

    def update_password(self, password, confirm_password, id):
        errors = []
        if self.password_invalid(password):
            errors.append("Password must be 8 characters or more")
        if self.password_not_match(password, confirm_password):
            errors.append("Passwords must match")
        if errors:
            return {'errors': errors}
        user = User.objects.get(id=id)
        user.hash_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        return {"user": user}

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    user_level = models.IntegerField()
    description = models.TextField(max_length=100, default="")
    email = models.CharField(max_length=255, unique=True)
    hash_pw = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

class Message(models.Model):
    content = models.TextField(max_length = 1000)
    sender = models.ForeignKey(User, related_name="sent_messages", default=None)
    receiver = models.ForeignKey(User, related_name="received_messages", default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    content = models.TextField(max_length = 1000)
    user = models.ForeignKey(User, related_name="user_comments")
    message = models.ForeignKey(Message, related_name="message_comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/user_dashboard/views.py
from django.shortcuts import render, redirect, reverse
from .models import *
from django.contrib import messages

def index(request):
    return render(request, 'user_dashboard/index.html')

def signin(request):
    return render(request, 'user_dashboard/signin.html')

def authenticate(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.login(email, password)
        if "errors" in user:
            for error in user["errors"]:
                messages.error(request, error)
            return redirect(reverse('dashboard:signin'))
        else:
            request.session["id"] = user["user"].id
            request.session["user_level"] = user["user"].user_level
            return redirect(reverse('dashboard:dashboard'))
    else:
        return redirect(reverse('dashboard:signin'))

def register(request):
    return render(request, 'user_dashboard/register.html')

def register_add(request):
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user = User.objects.add_user(first_name, last_name, email, password, confirm_password)
        if "errors" in user:
            for error in user["errors"]:
                messages.error(request, error)
            if request.session["user_level"] == 9:
                return redirect(reverse('dashboard:new'))
            return redirect(reverse('dashboard:register'))
        elif "id" not in request.session:
            request.session["id"] = user["user"].id
            request.session["user_level"] = user["user"].user_level
        return redirect(reverse('dashboard:dashboard'))
    else:
        if request.session["user_level"] == 9:
            return redirect(reverse('dashboard:new'))
        return redirect(reverse('dashboard:register'))

def logout(request):
    del request.session['id']
    del request.session["user_level"]
    return redirect(reverse('dashboard:index'))

def dashboard(request):
    if request.session["user_level"] == 9:
        return redirect(reverse('dashboard:dashboard_admin'))
    users = User.objects.all()
    context = {
            "users":users,
    }
    return render(request, 'user_dashboard/dashboard.html', context)

def dashboard_admin(request):
    if request.session["user_level"] == 1:
        return redirect(reverse('dashboard:dashboard'))
    users = User.objects.all()
    context = {
            "users":users,
    }
    return render(request, 'user_dashboard/dashboard_admin.html', context)

def show(request, id):
    try:
        user = User.objects.get(id=id)
    except:
        redirect(reverse('dashboard:dashboard'))
    context = {
            "user":user
    }
    return render(request, 'user_dashboard/show.html', context)

def edit(request):
    try:
        user = User.objects.get(id=request.session['id'])
    except:
        redirect(reverse('dashboard:dashboard'))
    context = {
            "user":user
    }
    return render(request, 'user_dashboard/edit.html', context)

def update(request, id):
    if request.POST["edit_field"] == "information":
        email = request.POST["email"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        if "user_level" in request.POST:
            user_level= request.POST["user_level"]
            user = User.objects.update_name(email, first_name, last_name, id, user_level)
        else:
            user = User.objects.update_name(email, first_name, last_name, id)
    elif request.POST["edit_field"] == "password":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user = User.objects.update_password(password, confirm_password, id)
    else:
        user = User.objects.get(id=request.session['id'])
        user.description = request.POST["description"]
        user.save()
        return redirect(reverse("dashboard:show", kwargs={'id':user.id}))
    if "errors" in user:
        for error in user["errors"]:
            messages.error(request, error)
            if "user_level" in request.POST:
                return redirect(reverse("dashboard:edit_admin", kwargs={'id':id}))
            return redirect(reverse('dashboard:edit'))
    return redirect(reverse("dashboard:show", kwargs={'id':id}))

def edit_admin(request, id):
    try:
        user = User.objects.get(id=id)
        context = {"user":user}
    except:
        redirect(reverse('dashboard:dashboard'))
    return render(request, 'user_dashboard/edit_admin.html', context)

def new(request):
    return render(request, 'user_dashboard/new.html')

def message(request, id):
    if request.method == "POST":
        content = request.POST["message"]
        sender = User.objects.get(id=request.session["id"])
        receiver = User.objects.get(id=id)
        Message.objects.create(content=content, sender=sender, receiver=receiver)
    return redirect(reverse('dashboard:show', kwargs={'id':id}))

def comment(request, user_id, message_id):
    if request.method == "POST":
        content = request.POST["comment"]
        user = User.objects.get(id=request.session["id"])
        message = Message.objects.get(id=message_id)
        Comment.objects.create(content=content, user=user, message=message)
    return redirect(reverse('dashboard:show', kwargs={'id':user_id}))

def delete_message(request, user_id, message_id):
    Message.objects.get(id=message_id).delete()
    return redirect(reverse('dashboard:show', kwargs={'id':user_id}))

def delete_comment(request, user_id, comment_id):
    Comment.objects.get(id=comment_id).delete()
    return redirect(reverse('dashboard:show', kwargs={'id':user_id}))

apps/user_dashboard/templates/user_dashboard/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="{% url 'dashboard:dashboard' %}">Home</a>
        <a class="navbar-right" href="{% url 'dashboard:logout' %}">Sign out</a>
        <a  href="{% url 'dashboard:show' id=request.session.id %}">Profile</a>
      </div>
    </nav>
    <h2>All Users</h2>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created At</th>
          <th>User Level</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td>{{user.id}}</td>
            <td><a href="{% url 'dashboard:show' id=user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
            <td>{{user.email}}</td>
            <td>{{user.created_at}}</td>
            <td>{% if user.user_level == 9 %}admin{% else %}normal{% endif %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </body>
</html>

apps/user_dashboard/templates/user_dashboard/dashboard_admin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="{% url 'dashboard:dashboard' %}">Home</a>
        <a class="navbar-right" href="{% url 'dashboard:logout' %}">Sign out</a>
        <a  href="{% url 'dashboard:show' id=request.session.id %}">Profile</a>
      </div>
    </nav>
    <h2>Manage Users</h2>
    <a class="btn btn-success" href="{% url 'dashboard:new' %}">Add new</a>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created At</th>
          <th>User Level</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td>{{user.id}}</td>
            <td><a href="{% url 'dashboard:show' id=user.id %}">{{user.first_name}} {{user.last_name}}</a></td>
            <td>{{user.email}}</td>
            <td>{{user.created_at}}</td>
            <td>{% if user.user_level == 9 %}admin{% else %}normal{% endif %}</td>
            <td><a href="{% url 'dashboard:edit_admin' id=user.id %}">edit</a> | <a href="#">remove</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </body>
</html>

apps/user_dashboard/templates/user_dashboard/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="{% url 'dashboard:dashboard' %}">Home</a>
        <a class="navbar-right" href="{% url 'dashboard:logout' %}">Sign out</a>
        <a  href="{% url 'dashboard:show' id=request.session.id %}">Profile</a>
      </div>
    </nav>
    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <h2>Edit Profile</h2>
    <div>
      <h4>Edit Information</h4>
      <form action="{% url 'dashboard:update' id=user.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="edit_field" value="information">
        <label for="email">Email Address: </label>
        <input type="text" name="email" value="{{user.email}}">
        <label for="first_name">First Name: </label>
        <input type="text" name="first_name" value="{{user.first_name}}">
        <label for="last_name">Last Name: </label>
        <input type="text" name="last_name" value="{{user.last_name}}">
        <input class="btn btn-success" type="submit" value="Save">
      </form>
    </div>
    <div>
      <h4>Change Password</h4>
      <form action="{% url 'dashboard:update' id=user.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="edit_field" value="password">
        <label for="password">Password: </label>
        <input type="password" name="password">
        <label for="confirm_password">Confirm: </label>
        <input type="password" name="confirm_password">
        <input class="btn btn-success" type="submit" value="Update Password">
      </form>
    </div>
    <div>
      <h4>Edit Description</h4>
      <form action="{% url 'dashboard:update' id=user.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="edit_field" value="description">
        <label for="description">Description: </label>
        <textarea name="description" rows="8" cols="80"></textarea>
        <input class="btn btn-success" type="submit" value="Save">
      </form>
    </div>
  </body>
</html>

apps/user_dashboard/templates/user_dashboard/edit_admin.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Profile</title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="{% url 'dashboard:dashboard' %}">Home</a>
        <a class="navbar-right" href="{% url 'dashboard:logout' %}">Sign out</a>
        <a  href="{% url 'dashboard:show' id=request.session.id %}">Profile</a>
      </div>
    </nav>
    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <h2>Edit User #{{user.id}}</h2>
    <a class="btn btn-primary" href="{% url 'dashboard:dashboard_admin' %}">Return to Dashboard</a>
    <div>
      <h4>Edit Information</h4>
      <form action="{% url 'dashboard:update' id=user.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="edit_field" value="information">
        <label for="email">Email Address: </label>
        <input type="text" name="email" value="{{user.email}}">
        <label for="first_name">First Name: </label>
        <input type="text" name="first_name" value="{{user.first_name}}">
        <label for="last_name">Last Name: </label>
        <input type="text" name="last_name" value="{{user.last_name}}">
        <label for="user_level">User Level</label>
        <select name="user_level" >
          <option value="1">Normal</option>
          <option value="9" {% if user.user_level == 9 %}selected{% endif %}>Admin</option>
        </select>
        <input class="btn btn-success" type="submit" value="Save">
      </form>
    </div>
    <div>
      <h4>Change Password</h4>
      <form action="{% url 'dashboard:update' id=user.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="edit_field" value="password">
        <label for="password">Password: </label>
        <input type="password" name="password">
        <label for="confirm_password">Confirm: </label>
        <input type="password" name="confirm_password">
        <input class="btn btn-success" type="submit" value="Update Password">
      </form>
    </div>

  </body>
</html>

apps/user_dashboard/templates/user_dashboard/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="">Home</a>
        <a class="navbar-right" href="">Sign in</a>
      </div>
    </nav>
    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <a class="btn btn-primary" href="{% url 'dashboard:dashboard_admin' %}">Return to Dashboard</a>
    <div>
      <h1>Add a new user</h1>
      <form action="{% url 'dashboard:register_add' %}" method="POST">
        {% csrf_token %}
        <label for="email">Email: </label>
        <input type="text" name="email">
        <label for="first_name">First Name: </label>
        <input type="text" name="first_name">
        <label for="last_name">Last Name: </label>
        <input type="text" name="last_name">
        <label for="password">Password: </label>
        <input type="password" name="password">
        <label for="confirm_password">Confirm: </label>
        <input type="password" name="confirm_password">
        <input class="btn btn-info" type="submit" value="Create">
      </form>
    </div>
  </body>
</html>

apps/user_dashboard/templates/user_dashboard/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a>Test App</a>
        <a href="{% url 'dashboard:dashboard' %}">Home</a>
        <a class="navbar-right" href="{% url 'dashboard:logout' %}">Sign out</a>
        <a  href="{% url 'dashboard:show' id=request.session.id %}">Profile</a>
      </div>
    </nav>
    {% if messages %}
      <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <h2>{{user.first_name}} {{user.last_name}}</h2>
    <div>
      <p>Registered at: {{user.created_at}}</p>
      <p>User ID: #{{user.id}}</p>
      <p>Email Address: {{user.email}}</p>
      <p>Description: {{user.description}}</p>
    </div>
    {% if request.session.id == user.id %}
      <a href="{% url 'dashboard:edit' %}">Edit My Profile</a>
    {% endif %}
    {% if request.session.user_level == 9 %}
      <a href="{% url 'dashboard:edit_admin' id=user.id %}">EDIT THIS USER</a>
    {% endif %}
    <h2>Leave a message for {{user.first_name}}</h2>
    <form action="{% url 'dashboard:message' id=user.id %}" method="post">
      {% csrf_token %}
      <textarea name="message" rows="8" cols="80" required></textarea>
      <input class="btn btn-success" type="submit" value="Post">
    </form>
    {% for message in user.received_messages.all %}
      <div class="message">
        <p><a href="{% url 'dashboard:show' id=message.sender.id  %}">{{message.sender.first_name}}</a> Wrote: </p>
        <h4>{{message.content}}</h4>
        <p>{{message.created_at}}</p>
        {% if message.sender.id == request.session.id or request.session.admin_level == 9  %}
          <a href="{% url 'dashboard:delete_message' user_id=user.id message_id=message.id %}">Delete this message</a>
        {% endif %}
      </div>
      <form action="{% url 'dashboard:comment' message_id=message.id user_id=user.id %}" method="post">
        {% csrf_token %}
        <textarea name="comment" rows="4" cols="60" required></textarea>
        <input class="btn btn-success" type="submit" value="Post">
      </form>
      {% for comment in message.message_comments.all %}
      <div class="comment">
        <p><a href="{% url 'dashboard:show' id=comment.user.id %}">{{comment.user.first_name}}</a> Wrote: </p>
        <h4>{{comment.content}}</h4>
        <p>{{comment.created_at}}</p>
        {% if comment.user.id == request.session.id or request.session.admin_level == 9  %}
          <a href="{% url 'dashboard:delete_comment' user_id=user.id comment_id=comment.id %}">Delete this comment</a>
        {% endif %}
      </div>
      {% endfor %}
    {% endfor %}
  </body>
</html>